# Generated by Django 3.1.1 on 2021-04-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=11)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Trans', 'Trans')], default='Male', max_length=7)),
                ('is_patient', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('speciality', models.CharField(choices=[('Cancer', 'Cancer'), ('Nephrologist', 'Nephrologist'), ('Diabetes & Endocrinology', 'Diabetes & Endocrinology'), ('cardiovascular', 'cardiovascular'), ('Normal_Physician', 'Normal_Physician')], default='Normal_Physician', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=11)),
                ('age', models.IntegerField()),
                ('problems', models.TextField()),
                ('medicine_given', models.TextField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Trans', 'Trans')], default='Male', max_length=7)),
                ('Primary_Physician', models.CharField(max_length=200)),
                ('Previous_treatment', models.TextField()),
                ('is_patient', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
