# Generated by Django 3.1.1 on 2021-04-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20210409_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_model',
            name='password',
            field=models.CharField(default='  ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor_model',
            name='slug',
            field=models.SlugField(default='', max_length=250, unique_for_date='publish'),
        ),
        migrations.AddField(
            model_name='patient_model',
            name='password',
            field=models.CharField(default=123456, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_model',
            name='slug',
            field=models.SlugField(default='', max_length=250, unique_for_date='publish'),
        ),
    ]
